### ISSUE TITLE
what are your thoughts on tracking on going events like user groups?

### ISSUE THREAD

**Issue by codersquid** [pyvideo/pyvideo#107]
Usergroups are ongoing versus conferences, which are not. This means that an issue to add a usergroup would be good to get all their past events, but future events are going to depend on me or someone tracking their sources of information and cleaning up the data after I grab it.

So, I could set up a periodic job to grab things from channels, but the information will be of varying quality, might not always be a python event, etc.

I know that Carl has tried to crowd source video information where he has volunteers check it before he flips a switch to post data to pyvideo. He's had very limited success with that.

So, it's a social and a technical challenge.

meta: Open ended issues aren't the best to have in an issue tracker, so we should come up with some done criteria for this particular issue so we don't end up with a weed. Maybe this issue can be closed when we have, say, 5 ideas? then we can have a wiki page or something for a backlog of ideas without needing to prune the issue tracker later.

**Comment by CarlFK** [comment]
I would add "contact name/email" and "feed url" to the category table.

contact is a reference so that a human can know who to contact.
I think a monthly automated "do you have new videos?" message is bad.

feed url is something that can be polled daily or weekly to check for
changes.
at first, alert the admins (will and skay) and who can just scrape the
updates and be done with it.

maybe in the future figure out how to automate something, but this is way
too fuzzy right now so stick with humans being alerted that there might be
work to do.



On Fri, May 1, 2015 at 8:28 AM, Sheila Miguez <notifications@github.com>
wrote:

> Usergroups are ongoing versus conferences, which are not. This means that
> an issue to add a usergroup would be good to get all their past events, but
> future events are going to depend on me or someone tracking their sources
> of information and cleaning up the data after I grab it.
>
> So, I could set up a periodic job to grab things from channels, but the
> information will be of varying quality, might not always be a python event,
> etc.
>
> I know that Carl has tried to crowd source video information where he has
> volunteers check it before he flips a switch to post data to pyvideo. He's
> had very limited success with that.
>
> So, it's a social and a technical challenge.
>
> meta: Open ended issues aren't the best to have in an issue tracker, so we
> should come up with some done criteria for this particular issue so we
> don't end up with a weed. Maybe this issue can be closed when we have, say,
> 5 ideas? then we can have a wiki page or something for a backlog of ideas
> without needing to prune the issue tracker later.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyvideo/pyvideo/issues/107>.
>



-- 
Carl K
