### ISSUE TITLE
talk statistics

### ISSUE THREAD

**Issue by codersquid** [pyvideo/pyvideo#125]
I saw this interesting tweet about speaker/gender breakdown.

https://twitter.com/elliewix/status/629080869836353536

It could be neat to have a stats page per category groups, or the whole site, with tables about speakers or other things we can analyse about talks.

**Comment by elliewix** [comment]
I'm prepping a blog post that talks about the data and my analysis.  I ended up having to do a bunch of hand coding to resolve some of the gender values that pretty seriously changed the values.  Running the tool over the data in an automated way could produce interesting results, but I wouldn't want it to be standalone without caveats.  Particularly when talking about assigning individuals gender values.

I was meaning to contact you because I would like to make the data file publicly available for anyone to use but I don't want to violate any presenter consents that were put into place.  The entire project is up in a private repo now I can invite you to view.

**Comment by willkg** [comment]
The data is entirely public. There's no consents or contracts I've entered into with anyone.

How'd working with the API go? Are there things we can do to make pulling the data down easier?

Also, thank you for working on this!

**Comment by elliewix** [comment]
Wonderful!  I'll sort out which repository I'd like to go with once I'm ready.  Likely Zenodo so I can link it to the existing github repo. Anyhoo...

The API was interesting.  I downloaded one JSON file I thought had all the video links but it only had ~2700ish.  So I ended up brute forcing range(2, 3667) with the JSON download link to get everything.  I got lovely 404 errors on things that didn't exist, so it was straight forward that way.

Maybe I missed it, but it would have been nice to see some documentation on where the data lived or a list of all the valid video IDs.  Not impossible, though, and the JSON files I got were easy enough to work with.
