### ISSUE TITLE
Update  401 

### ISSUE THREAD

**Issue by CarlFK** [pyvideo/pyvideo#132]
Trying to store the video URLs to http://www.pyvideo.org/video/3717/more-lightning-talks

```
  File "add_to_richard.py", line 157, in update_richard
    video_id=v_id)
  File "/home/juser/.virtualenvs/veyepar/local/lib/python2.7/site-packages/steve
/richardapi.py", line 108, in get_video
    return restapi.get_content(api.video(video_id).get(auth_token=auth_token))
  File "/home/juser/.virtualenvs/veyepar/local/lib/python2.7/site-packages/steve
/restapi.py", line 201, in get
    resp = self._request('GET', params=kwargs, headers=headers)
  File "/home/juser/.virtualenvs/veyepar/local/lib/python2.7/site-packages/steve
/restapi.py", line 190, in _request
    response=resp)
steve.restapi.Http4xxException: HTTP  : GET http://pyvideo.org/api/v2/video/37
17/
```

 http://pyvideo.org/api/v2/video/3717/
HTTP 404 NOT FOUND
...
{
    "detail": "Not found"

**Comment by willkg** [comment]
I talked to @CarlFK about this on IRC. We talked about things and discovered many exciting things about the richard api and possibly steve that made me feel icky inside. We should rewrite everything.

But... it turned out to be a problem with @CarlFK's script possibly exacerbated by icky things in the richard api and steve.

It was an exciting opportunity for spelunking in the dark antediluvian caves of the richard api.
