### ISSUE TITLE
remove video from http://pyvideo.org

### ISSUE THREAD

**Issue by vwoloszyn** [pyvideo/pyvideo#153]
I would like to remove my video from pyvideo.org. I am asking this issue here because the website does not provide any way to do that. 
http://pyvideo.org/speaker/vinicius-woloszyn.html
Thank you very much in advance.

**Comment by Daniel-at-github** [comment]
Will fix in https://github.com/pyvideo/data/issues/500. You can close it here.

**Comment by vwoloszyn** [comment]
full link for that http://pyvideo.org/scipyla-2016/a-simplificacao-textual-como-instrumento-de-inclusao-cognitiva.html

**Comment by Daniel-at-github** [comment]
Web updated ( https://github.com/pyvideo/pyvideo/pull/154 ) now it shows an error 404 page.
The data is not erased from the repository because we can't remove it from source https://www.youtube.com/watch?v=F_i0KJ4VOu4 or from the list https://www.youtube.com/playlist?list=PLfVc-mR8AkU1ZOYwkDLtv62IOWRuZrxlM and prevents it from been corrected at later time and reincorporated again.

**Comment by redapple** [comment]
@vwoloszyn , I'm closing this issue.
Is what @Daniel-at-github commented https://github.com/pyvideo/pyvideo/issues/153#issuecomment-393998139 ok with you?

**Comment by vwoloszyn** [comment]
Hi all. The video is still on youtube. How can I delete it?

**Comment by redapple** [comment]
@vwoloszyn , PyVideo is not the publisher of the videos listed.
You will have to contact the owner of that YouTube channel, SciPy Latin America (see https://www.youtube.com/channel/UClb88lwUvlFikmhTzVGsVGA/about), or YouTube directly for that particular video to be removed.

**Comment by vwoloszyn** [comment]
ok. thank you for the information.
