### ISSUE TITLE
use the language codes of wikipedia

### ISSUE THREAD

**Issue by szabgab** [pyvideo/pyvideo#255]
For example Spanish is `es` on Wikipedia and not `spa` as it is on PyVideo.
See the language links here: https://www.wikipedia.org/

If you agree to this change I can implement it.

If you accept  #253  you'll see there are a number of videos that are marked with incorrect language tags. (e.g 'en' instead of 'eng' and 'it' instead of 'ita'. I'll fix those, but IMHO it would be better to already fix them in the new direction. That is, convert all the 'ita' to 'it'.

**Comment by redapple** [comment]
hi @szabgab , thanks you bringing this up.

The "language" field in videos JSON files is defined as [ISO 639-3 language code](https://github.com/pyvideo/data/blob/355bd8c30737194d56b8627d4d04c38ed4d8c4c4/.schemas/video.json#L30), i.e. [3-letter language codes](https://en.wikipedia.org/wiki/ISO_639-3).

[ISO 639-2 codes](https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes) are certainly more common but 639-3 do cover more languages
> ISO 639-3 extends the ISO 639-2 alpha-3 codes with an aim to cover all known natural languages

This choice is of course debatable.

My preference would be to fix the 2-letter codes into their 3-letter equivalent instead of changing the other way round.

**Comment by szabgab** [comment]
Thanks for the reply @redapple 
I did not realize the 3-letter codes were another standard.
In that case let's stick to the ISO 639-3. I'll make the changes in that direction.
