### ISSUE TITLE
pycon-odessa-2019 aleksei-borisenko... not generated

### ISSUE THREAD

**Issue by Daniel-at-github** [pyvideo/pyvideo#256]
Pyvideo/data have data for [pycon-odessa-2019 aleksei-borisenko... ](https://github.com/pyvideo/data/blob/master/pycon-odessa-2019/videos/aleksei-borisenko-setevaia-programmiruemost-s-ispolzovaniem-python-ua.json) but nothing is generated (See https://pyvideo.org/events/pycon-odessa-2019.html)
In https://github.com/pyvideo/pyvideo_scrape/pull/1 fix proposal tackles the issue but applying it to Pyvideo/data reserialize causes 5571 changes.

Is it OK to make this mentioned 5571 changes? Anyone knows how to fix it in  pyvideo/pyvideo ?

**Comment by redapple** [comment]
Today March 17, I can see talks listed for PyCon Odessa 2019:
![image](https://user-images.githubusercontent.com/886296/76875585-0902e800-6871-11ea-95be-aafc61d8a546.png)

and the links do lead to talk pages.

The problem mentioned in https://github.com/pyvideo/pyvideo_scrape/pull/1 looks related to how [pyvideosearch](https://github.com/zerok/pyvideosearch) generates URLs. The filename should be enough to generate the link. Using the title to re-slugify is probably where the issue is.

ensure-ascii/"\uXXXX"-escaping is valid JSON (and the default with standard `json` package), I would rather we do not change that.

**Comment by Daniel-at-github** [comment]
Closed while no more similar cases
