### ISSUE TITLE
Djangocon US 2013 videos ?

### ISSUE THREAD

**Issue by vigo** [pyvideo/pyvideo#279]
Links are broken :(

https://pyvideo.org/events/djangocon-us-2013.html

**Comment by logston** [comment]
Oh no! Looking into this, it looks like the videos have been removed from Youtube. Perhaps they were moved? 

@jefftriplett do you know if the djangocon us 2013 youtube videos have been moved?

**Comment by jefftriplett** [comment]
I'm afraid this is several years before I had anything to do with DjangoCon US or the non-profit. One of the previous organizers must have deleted it since this predates us even having a YouTube page to store stuff. 

If you stumble on a backup somewhere, please let me know and we can probably reload them on YouTube and Archive.org.

**Comment by vigo** [comment]
https://web.archive.org/web/20171229054325/https://pyvideo.org/events/djangocon-us-2013.html

but it's almost impossible to reach videos.

**Comment by logston** [comment]
I'm sorry @vigo, but after searching archive.org and not finding anything, I'm not sure what more we can do about this.

**Comment by vigo** [comment]
thanks for the effort.

**Comment by logston** [comment]
Thanks for understanding.
