### ISSUE TITLE
Make pyvideo more "fork friendly"

### ISSUE THREAD

**Issue by Daniel-at-github** [pyvideo/pyvideo#59]
Hi,

I'm trying to fork pyvideo to use it as the video index for my zone local meetups. Only one is python related (php, java, javascript, joomla, ...) the other can't get into pyvideo.

I think that expanding it use to other communities will attract more contributors, user base and give more visibility to the project.
But I'm not sure how to:
* Change the domain.
* Configure travis.
* Deploy.

My suggestions:
* Parametrize pyvideo with a yaml config file (web_url, repo, ...).
* Convert the Makefile to a fabfile (from make to python fabric).
* Document the fork/deploy process.
* Try it with your zone local meetups.

**Comment by lgh2** [comment]
I think this is a good suggestion, and I would like to discuss it with @logston  to see what he thinks.

**Comment by logston** [comment]
Hi @Daniel-at-github! I'd love to make this platform more available, however, I'm not sure our time would be well-spent re-documenting our current process since it is a pretty vanilla set up. 

- The domain is determined by regular DNS rules and github pages domain naming rules via the CNAME file. 
- The travis setup is configured via yaml file and is in the root of the repo. The deploy process is triggered by a simple webhook request sent from GitHbu to Travis when our `master` branch is updated. 

@Daniel-at-github I would be more than happy to jump on a skype call to cover all of this in detail if you'd like. 

Dev-ops via fabric can end up being a very large project and a lot of maintenance, thus I'm cautious about converting away from our current setup. 

Would love to chat more about this @Daniel-at-github, feel free to reach out.

**Comment by willkg** [comment]
One of the things I sort of regret when working on the previous PyVideo was spending the time generalizing the software so that other people could use it. Those efforts were substantial, but never panned out in any way. Clearly, that's anecdata, but it covers several years of experience.

I would suggest that anyone who wants to make this fork-friendly, should fork it themselves and then spend the effort to make it fork-friendly in the fork. Then @logston and crew can pull down changes as they see fit.

**Comment by Daniel-at-github** [comment]
Thanks for the explanation @logston. I will give it another try.

My english is not good enough to use it in interactive real time, but if you ever give a (lightning?) talk about it, please post it in pyvideo.

I see the point @willkg is making. If the fork succeeds I will make a pull request to include it in the about page. :smile:

**Comment by logston** [comment]
Thanks for the suggestion and initiative @Daniel-at-github!
