### ISSUE TITLE
please add an SSL cert

### ISSUE THREAD

**Issue by dnozay** [pyvideo/pyvideo#73]
Hello,

Let's Encrypt / Certbot can be used to request a free SSL certificate: https://certbot.eff.org/
This would make sure there are no MITM attacks to redirect users to unsafe content.

Thank you.

**Comment by zerok** [comment]
I think the main roadblock here is that you cannot use TLS when using custom domains for GitHub hosted sites. Correct me if I'm wrong about this please 🙂

**Comment by dnozay** [comment]
Are you referring to https://github.com/isaacs/github/issues/156?

**Comment by Daniel-at-github** [comment]
You cannot use TLS when using custom domains for GitHub https://help.github.com/articles/securing-your-github-pages-site-with-https/
But you can do it with gitlab pages https://about.gitlab.com/2016/06/24/secure-gitlab-pages-with-startssl/

**Comment by dirn** [comment]
>But you can do it with gitlab pages

Unfortunately, at least for the time being, this process requires manually updating certificate. While that isn't necessarily a huge deal, the process currently requires removing the custom domain and adding it again with the new certificate. It's been raised [1][2], but there is no solution yet.

This down time may be a non-starter for high traffic sites.

[1] https://gitlab.com/gitlab-org/gitlab-ee/issues/1332
[2] https://gitlab.com/gitlab-org/gitlab-ce/issues/29720

**Comment by zerok** [comment]
IMHO having PyVideo every once in a while not being responsive for a minute or two shouldn't be considered a show-stopper. We are not hosting a service for the emergency services after all 😄

**Comment by logston** [comment]
Totally down for this happen, just running out of time! Does anyone want to take the initiative here? If not, I'll start to pull resources.

**Comment by zerok** [comment]
OK, so what's the approach we want to take here? Gitlab or self-hosted?

**Comment by lgh2** [comment]
What would be the advantages/disadvantages of each?  Can we get a grant from the PSF to cover hosting fees if we self-host?

**Comment by zerok** [comment]
The main advantage of going self-hosted would be flexibility. We could more freely add additional things to our toolchain (like the search feature I've implemented and that is now hosted on one of Ulrich's servers). We could also handle the deployments more easily without relying on Travis.

The downsides would be additional costs and maintenance overhead. The latter is negligible, though in my opinion, as the main deployment is a static one right now.

**Comment by logston** [comment]
I have a number of thoughts feelings around this. 

1. Do we really want to maintain our own infrastructure?

I'm not sure who's shoulders this responsibility would fall on but maintaining our own box(es) is a non-trivial task. Yes, it would be (for now) just a box with Nginx and the repo (and @zerok's search engine) but that list would not stop there. And when it goes down, we would be down until someone fixed it. That means holidays, weekends, and other precious times would be at risk. One of our main goals with this projects was to keep it simple and moving to a box does not push us in that direction. I strongly believe that the success of this project depends on its simplicity. There simply isn't enough need for this site to warrant a large amount of dev ops in my opinion. 

Also, I'd like to note that GitHub does some awesome caching (CDN) stuff for us that we would not get for free with a box. In fact, we'd have to replicate it to get the same level of service to users. So without adding another level to our stack, our performance would drop worldwide after such a migration to our own box. 

TravisCI would not be out of the picture either. We would still want an automatic deploy process which would require some sort of TravisCI magic. 

Finally, for this section, is job handoff. At a certain point, whoever is taking care of this now is not going to want to take care of it later. No one lasts forever and we should plan for that in a couple of ways. 

- Easy to learn stack
- Great docs (the more complex the stack, the better the level of documentation needs to be)

Thus, to implement this move to a box, we would need to document its setup in a detailed enough way such that a newbie to the project could grasp in a relatively short period of time. Also, again, we would have to maintain those docs. 

2. Do we really need HTTPS? All we service is GETs. 

Before we start planning for an attack, is this the attack we are most susceptible to? I would hate to move us to a box to avoid one threat only to find out we are now much more susceptible to another threat; specifically DDoS.

In my experience, MITM attacks are not very common and somewhat hard to pull off. DDoS attacks however are like spilled milk at a table full of toddlers; it's going to happen and probably soon. 

I really like the idea of HTTPS for privacy reasons. I might be over paranoid here but the idea of certain governments or other interested parties knowing what I am searching seems like an invasion of privacy. However, I recognize that this may be a bit paranoid for the type of content our site carries. Thus, I don't think it's wise to make major shifts in stack for this benefit alone.

3. I'm for HTTPS but maybe not at the costs that I can see.

Adding all these benefits and costs up, I feel that it would be in our best interest to stay with our GitHub based deployment system rather than moving to a box. 

I have heard that GitLab provides a lot of the same services that GitHub provides as well as HTTPS. Would someone be interested in looking at GitLab? We wouldn't even need to move our code base. We could simply mirror or deploy to GitLab rather than GitHub via TravisCI.

**Comment by lgh2** [comment]
I was describing this issue to a friend of mine, and he suggested the following: 
https://hackernoon.com/set-up-ssl-on-github-pages-with-custom-domains-for-free-a576bdf51bc

It appears that Cloudflare will give you ssl encryption for a custom, github-hosted domain.  Much as I dislike Cloudflare, if this works I think it will be a solution that will give us ssl encryption with a minimum of effort.

**Comment by dirn** [comment]
>In my experience, MITM attacks are not very common and somewhat hard to pull off. DDoS attacks however are like spilled milk at a table full of toddlers; it's going to happen and probably soon.
>
>I really like the idea of HTTPS for privacy reasons. I might be over paranoid here but the idea of certain governments or other interested parties knowing what I am searching seems like an invasion of privacy. However, I recognize that this may be a bit paranoid for the type of content our site carries. Thus, I don't think it's wise to make major shifts in stack for this benefit alone.

This may seem paranoid, but it is a very real thing that happens. [Wikipedia recently switched to SSL-only for these very reasons.](https://motherboard.vice.com/en_us/article/a3wbgz/wikipedias-switch-to-https-has-successfully-fought-government-censorship)

>We could simply mirror or deploy to GitLab rather than GitHub via TravisCI.

You don't even need Travis CI for that. [GitLab can do it for you.](https://docs.gitlab.com/ee/workflow/repository_mirroring.html#pulling-from-a-remote-repository)

**Comment by logston** [comment]
Great. Progress: https://gitlab.com/pyvideo/pyvideo.gitlab.io

**Comment by logston** [comment]
@lgh2 are you on GitLab? Would like to give you permissions to this repo.

**Comment by lgh2** [comment]
I just signed up.  My username is laurahampton.

**Comment by ajdavis** [comment]
Hi! I see that the current state is, https://pyvideo.org presents a github.io certificate, which of course is mistrusted by my browser.

**Comment by logston** [comment]
Dang. Thanks @ajdavis. Looking into this.

**Comment by Daniel-at-github** [comment]
Can I take a look with https://gitlab.com/daniel-at-internet ?

**Comment by logston** [comment]
@Daniel-at-github Sure thing. I'm looking into it now too.

**Comment by logston** [comment]
Looks like we would need to update the cert every few months on GitLab (assuming we would use letsencrypt)

![screen shot 2017-11-08 at 6 13 01 pm](https://user-images.githubusercontent.com/2641765/32579912-ee2abd70-c4b0-11e7-8b8e-f62afd388b5f.png)

**Comment by dirn** [comment]
@logston it's a bit more than just updating the cert. See https://github.com/pyvideo/pyvideo/issues/73#issuecomment-307502207.

**Comment by logston** [comment]
Yeah, thanks @dirn. The reality of "manually updating the cert" hit me and posted to remind myself.

**Comment by logston** [comment]
Long over due, but we are now https.

**Comment by ajdavis** [comment]
w00t!
