### ISSUE TITLE
Video tabs don't hide the second tab content

### ISSUE THREAD

**Issue by Daniel-at-github** [pyvideo/pyvideo#94]
As seen in #93, when there are more than one video source the tabbed interface shows the content of more of one tab.

Examples:

PyCon US 2013
[How to Except When You're Excepting](http://pyvideo.org/pycon-us-2013/how-to-except-when-youre-excepting.html)
Fri 15 March 2013
By Esther Nam

![imagen](https://user-images.githubusercontent.com/4407929/28993726-a77abaee-79bd-11e7-9b20-fbedac013aa8.png)

PyCon US 2013
[How the Internet works](http://pyvideo.org/pycon-us-2013/how-the-internet-works.html)
Fri 15 March 2013
By Jessica McKellar

![imagen](https://user-images.githubusercontent.com/25675821/28991514-ba3e9a68-793d-11e7-9ed7-9d498e37bece.png)

**Comment by JulienPalard** [comment]
Spotted the issue here https://pyvideo.org/pycon-fr-2019/comment-faire-confiance-aux-metadonnees-de-musique.html

3 tabs, 3 videos, but the 3 videos are "stacked veritcally" in the first tab.
![Screenshot_2020-03-13 Comment faire confiance aux métadonnées de musique](https://user-images.githubusercontent.com/239510/76626142-e43d0680-6538-11ea-86dd-1015b21ceb88.png)

**Comment by JulienPalard** [comment]
Thanks @redapple for fixing this!!
